### ISSUE TITLE
not work domain 4 level aka a.b.domain.com

### ISSUE THREAD

**Issue by constantineav** [rekby/lets-proxy2#100]
not work domain 4 level aka a.b.domain.com
[log.txt](https://github.com/rekby/lets-proxy2/files/3956980/log.txt)

**Comment by rekby** [comment]
Hello, thanks. I will check it.

**Comment by rekby** [comment]
I have check domains a.b.domain.com and a-v.dev.5commcomm.com in tests, both domain works.

For your domain log doesn't contains all records for connection afc05a48-187b-42a3-9979-45d851f58cbc (connection with try to issue certificate).

It finished at "Start order authorization", but must contains lines: "Create authorization order" and  last record: "Connection closed".

Try your domain again with version v0.22.4 - it contains some logging improove (log panics).
And send log again please.

**Comment by constantineav** [comment]
I conducted different tests. Yes, the problem is not confirmed. This is on my side somewhere there was a mistake. I apologize.
