### ISSUE TITLE
Add support for a fallback certificate

### ISSUE THREAD

**Issue by jasongill** [rekby/lets-proxy2#125]
Currently, if there is any problem issuing a certificate, the connection is dropped and a warning is logged - "Can't issue certificate".

For my use case, it would be preferable for the connection to continue using an existing certificate that we provide - not an automatically-issued letsencrypt certificate. This way, development or testing environments, or situations where letsencrypt isn't working properly, or other unusual cases can function without the connection just dropping.

I am using the attached patch to load our "fallback" certificate which is used if a letsencrypt certificate cannot be issued, but it's not very well written as I'm not very familiar with Go - it was pieced together by copying bits of the existing code, and relies on having a hard-coded filename.

I'd be happy to donate a small amount to support getting this functionality properly added as a configuration option, so that a fallback certificate could be selected (or possibly a mapping of existing domain patterns to certificate files, to skip the letsencrypt logic all together for some incoming connections) and used as opposed to just hanging up.

Thanks for all your hard work on this project!

```
diff --git a/internal/cert_manager/manager.go b/internal/cert_manager/manager.go
index 0344535..0cdc1e3 100644
--- a/internal/cert_manager/manager.go
+++ b/internal/cert_manager/manager.go
@@ -202,7 +202,13 @@ func (m *Manager) GetCertificate(hello *tls.ClientHelloInfo) (resultCert *tls.Ce
 			zap.Time("expire", res.Leaf.NotAfter))
 		return res, nil
 	}
-	logger.Warn("Can't issue certificate", zap.Error(err))
+	logger.Warn("Can't issue certificate, falling back to default", zap.Error(err))
+	fallback, err := tls.LoadX509KeyPair("fallback.crt", "fallback.key")
+	if err == nil {
+		return &fallback, nil
+	}
+
+	logger.Error("Can't fallback, giving up", zap.Error(err))
 	return nil, errHaveNoCert
 
 }
```

**Comment by rekby** [comment]
Hello @jasongill, thanks for your patch.
Fallback certificate will be difficult to use in cases, when lets-proxy handle many different domains - it will need cert for every domain.

And if you already have certificate - no need get new from lets encrypt.

I can offer you two options:
1. Lock certificates - you can create .lock file and .crt .key files for handle cert. 
For example if you want use your RSA certificate for domain.com: create in storage folder files
1.1. domain.com.lock (flag-file need file exist only - is can have any content of may be empty)
1.2. domain.com.rsa.key - private key
1.3. domain.com.rsa.cer - certificate (chained if need).
if .lock file exist for domain - let's proxy will use stored certificate without any check and without try to connect with lets-encrypt.

2. I can add option for use self-signed certificate when can't issue lets-encrypt cert.


Option 1 work now and you can use it.
Option 2 I can add.

**Comment by jasongill** [comment]
@rekby  thanks, I must be using an older version and wasn't aware of those lock files - do those work for wildcard domains/certificates? Being able to specify a self-signed certificate (or any certificate) is exactly what we are doing with my patch, although we use a commercial wildcard certificate as opposed to a self-signed cert as our use case puts everything under a "fallback" domain. But I will try out the lock files, thank you! 👍

**Comment by rekby** [comment]
Lock certificates can be use since start lets-proxy2.

You can use any certificate as locked - lets-proxy don't check any way, and yes - you can use wildcard cert as locked cert. But .domain.com.rsa.cer will use only for domain.com and www.domain.com.

You can set your own set of subdomains (instead www) https://github.com/rekby/lets-proxy2/blob/ee04435426a5d50f4841b1f21c01310c0cb6980f/cmd/static/default-config.toml#L17 but not it can't handle wildcard.

**Comment by jasongill** [comment]
Sounds good, thank you - I will play with that and keep an eye on future versions for new features. Thanks so much for your hard work on this project!
