### ISSUE TITLE
Must be cert exactly one: cert or last error

### ISSUE THREAD

**Issue by rekby** [rekby/lets-proxy2#134]
`2020-06-26T17:30:59.857Z	dpanic	cert_manager/cert-state.go:51	Must be cert exactly one: cert or last error. Cert set as nil.	{"connection_id": "31d1f03c-e30f-4e40-877c-dd46f43d6573", "domain": "www.pueblonuevomexicanrestaurant.com (punycode:www.pueblonuevomexicanrestaurant.com)", "cert_name": "
`

**Comment by rekby** [comment]
@realleoman, can you send me log | grep 31d1f03c-e30f-4e40-877c-dd46f43d6573 - for debug error?

**Comment by realleoman** [comment]
ubuntu@ip-10-0-1-246:~/ssl/lets-proxy2/log$ cat lets-proxy2.log | grep 31d1f03c-e30f-4e40-877c-dd46f43d6573
2020-06-26T17:30:59.857Z	dpanic	cert_manager/cert-state.go:51	Must be cert exactly one: cert or last error. Cert set as nil.	{"connection_id": "31d1f03c-e30f-4e40-877c-dd46f43d6573", "domain": "www.pueblonuevomexicanrestaurant.com (punycode:www.pueblonuevomexicanrestaurant.com)", "cert_name": "pueblonuevomexicanrestaurant.com.ecdsa", "certificate": "tls nil"}
2020-06-26T17:30:59.857Z	dpanic	cert_manager/manager.go:924	Panic handled	{"connection_id": "31d1f03c-e30f-4e40-877c-dd46f43d6573", "domain": "www.pueblonuevomexicanrestaurant.com (punycode:www.pueblonuevomexicanrestaurant.com)", "panic": "runtime error: invalid memory address or nil pointer dereference”}

I am attaching the log and the config file as well.

I have setup the nginx with this configuration to automatically generate the CERT files for all the domains we host in the server.

    # lets-proxy and lets-encrypt domain validation
    location ^~ /.well-known/acme-challenge/ {
      proxy_pass       http://127.0.0.1:4443;
      proxy_set_header Host      $host;
      proxy_set_header X-Real-IP $remote_addr;
    }





Saludos Cordiales,

**Comment by rekby** [comment]
>     # lets-proxy and lets-encrypt domain validation

It isn't need in lets-proxy2 - it support protocol with TLS authentications - similar early versions of first lets-proxy.

About log: can you change log level to debug and send log from any connection with panic message or with message "Must be cert exactly one: cert or last error"?

**Comment by realleoman** [comment]
Find log attached.  No panic issue was shown at this momento but there are several entries with error and no ver files were generated (I think)


Saludos Cordiales,

**Comment by realleoman** [comment]
@rekby  I only need to make sure **lets-encrypt2** is properly installed in my server and make sure it is working with API V2 and generating the certificates correctly.   How can I make sure this is happening at my end?

**Comment by rekby** [comment]
you write log with warning level, but I can't see trace with that level and need debug level for know way of error.

You can try curl https://your-domain if it works - than lets-proxy2 work.

**Comment by realleoman** [comment]
Hi Timoffe:

I finally enabled the debug level for logging. Hope you can take a quick look.  (zipped afile attached)

Looks like I have the lets-proxy2 now working locally (but I haven’t installed it as a service yet).

One question: How can I change the signing algorithm  from ECDSA to RSA?




Saludos Cordiales,

**Comment by rekby** [comment]
> One question: How can I change the signing algorithm  from ECDSA to RSA?
It is auto-selected by SSL-handshake.

If client support ECDSA - lets-proxy create/use ecdsa certificate else - rsa.

**Comment by rekby** [comment]
> I finally enabled the debug level for logging. Hope you can take a quick look.  (zipped afile attached)

You twice wrote about attach files, but I don't see files in ticket or my email.

**Comment by realleoman** [comment]
Hi Timoffee:

I attached log file and config file to your email now. You can check it in there

You have built such an amazing software!!! Thank You





Saludos Cordiales,

**Comment by realleoman** [comment]
> > One question: How can I change the signing algorithm  from ECDSA to RSA?
> > It is auto-selected by SSL-handshake.
> 
> If client support ECDSA - lets-proxy create/use ecdsa certificate else - rsa.

For this answer:
1) Is it possible to force Lets-Proxy2 to generate RSA instead of ECDSA certificate?

I have a lot of sites created in the past with RSA algorithm and I need to reuse them to keep their original creation dates.
