### ISSUE TITLE
Too many open files issue

### ISSUE THREAD

**Issue by realleoman** [rekby/lets-proxy2#135]
Hi @rekby 

I managed to install the `lets-proxy2` service but from time to time, it stops working and the log shows this entry: 

**Close listener	{"local_addr": "[::]:443", "error": "accept tcp [::]:443: accept4: too many open files"}**

Any suggestion how to fix those?

My entry looks like this in the config.toml file
```
# Seconds for issue every certificate. Cancel issue and return error if timeout.
IssueTimeout = 300

# For prevent infinite loop and consume all memory if cycle in includes
MaxConfigFilesRead = 30000

# After KeepAliveTimeoutSeconds of inactive incoming connection will close.
KeepAliveTimeoutSeconds = 900


```

Current Log error:

```
2020-06-30T03:50:15.933Z	error	tlslistener/tlslistenershandler.go:117	Close listener	{"local_addr": "[::]:443", "error": "accept tcp [::]:443: accept4: too many open files"}
github.com/rekby/lets-proxy2/internal/log.infoError
	/home/travis/gopath/src/github.com/rekby/lets-proxy2/internal/log/log.go:170
github.com/rekby/lets-proxy2/internal/log.InfoError
	/home/travis/gopath/src/github.com/rekby/lets-proxy2/internal/log/log.go:107
github.com/rekby/lets-proxy2/internal/tlslistener.handleConnections
	/home/travis/gopath/src/github.com/rekby/lets-proxy2/internal/tlslistener/tlslistenershandler.go:117
2020-06-30T03:50:15.934Z	error	cmd/main.go:169	Handle request stopped	{"error": "listener closed"}
github.com/rekby/lets-proxy2/internal/log.debugError
```

**Comment by rekby** [comment]
Hello.
You can decrease KeepAliveTimeoutSeconds - for close inactive connections faster or increase open file limit (by command ulimit or in sysctl files).

**Comment by realleoman** [comment]
Thank you @rekby

**Comment by brandymedia** [comment]
@realleoman how did you end up resolving this issue?

I've been encountering this intermittently for a while and I just end up restarting the service manually each time which is not ideal.

Thanks
