### ISSUE TITLE
Order authorization error 

### ISSUE THREAD

**Issue by realleoman** [rekby/lets-proxy2#136]
Hi @rekby 

Hope you help me with these two issues: A lot of records are showing these two entries in my log files: **order authorization error** and **429 : 429 Too Many Requests** and they can't be accessible from the Internet.

How could I fix this?

`2020-06-30T12:47:43.528Z	error	log/log.go:193	Can't get certificate from local state	{"connection_id": "955d6089-bff1-43ab-84b7-18031aa8e0bb", "domain": "www.fortlauderdalepestcontrolcompany.com (punycode:www.fortlauderdalepestcontrolcompany.com)", "cert_name": "fortlauderdalepestcontrolcompany.com.ecdsa", "error": "order authorization error"}`

`2020-06-30T12:48:28.272Z	error	cert_manager/manager.go:425	Create authorization order.	{"connection_id": "0ee08216-17ab-4b5d-a2a8-bc2f41befcd1", "domain": "excaliburcateringandbanquethall.com (punycode:excaliburcateringandbanquethall.com)", "cert_name": "excaliburcateringandbanquethall.com.ecdsa", "error": "429 : 429 Too Many Requests"}`

**Comment by rekby** [comment]
You have a lot of domains.
Problem was solved by copy certificates from old version lets-proxy and disable ECDSA (for reuse existed certificates).

**Comment by brandymedia** [comment]
Hey @realleoman did you ever find a solution to the "order authorization error" issue please?

I've encountered the same issue on a domain that was previously requesting a lot of certificates on spurious domain names.

I now can't get it to get a certificate on the www or naked versions.

Cheers
