### ISSUE TITLE
Too many redirects

### ISSUE THREAD

**Issue by adviserportals** [rekby/lets-proxy2#140]
I have this set up running as a service.

We use a .htaccess file to force https - this however, gives an error in the browser of 'Too Many Redirects".

The .htaccess files is as below:

````
<IfModule mod_rewrite.c>
RewriteEngine On

RewriteCond %{HTTP:X-FORWARDED-PROTO} !(^.+)
RewriteRule ^(.*)$ https://%{HTTP_HOST}/$1 [L,R=301]

RewriteBase /
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME}/index.html !-f
RewriteCond %{REQUEST_FILENAME}/index.php !-f
RewriteRule . index.php [L]
</IfModule>
````

**Comment by adviserportals** [comment]
Removing
````
RewriteCond %{HTTP:X-FORWARDED-PROTO} !(^.+)
RewriteRule ^(.*)$ https://%{HTTP_HOST}/$1 [L,R=301]
````
Seems to fix the issue.

Does lets-proxy2 automatically forward all http traffic to https automatically?

In lets-proxy (vs 1) we used to have to use the above code to make sure all traffic redirected to https...

**Comment by adviserportals** [comment]
@rekby wow! You are seriously amazing!

I've just pulled down the latest release and it works! Thank you so much.

I'm going do some more testing tomorrow before rolling it out in production but so far all is good.

👍🏻😁

**Comment by rekby** [comment]
reason cause in default headers - lets-proxy set default headers, but lets-proxy2 don't. 

It can be configured in config file, but it it good to have common headers by default.
