### ISSUE TITLE
NET::ERR_CERT_AUTHORITY_INVALID

### ISSUE THREAD

**Issue by adviserportals** [rekby/lets-proxy2#142]
I recently moved from vs1 to vs2 of 'lets-proxy' and in the main this is working.

However, I've noticed that occasionally I'll get the below error:

```
NET::ERR_CERT_AUTHORITY_INVALID
```

Looking in console, I can see the following information:
```
Issuer: Let's Encrypt Authority X3
Expires on: 4 Nov 2020
Current date: 6 Aug 2020
This page is not secure (broken HTTPS).

Certificate - missing
This site is missing a valid, trusted certificate (net::ERR_CERT_AUTHORITY_INVALID).

Connection - secure connection settings
The connection to this site is encrypted and authenticated using TLS 1.3, X25519, and AES_128_GCM.

Resources - all served securely
All resources on this page are served securely.
```
Looking in the 'lets-proxy' logs I can see:
```
"error": "remote error: tls: unknown certificate"
```
It seems as though it is saying the site connection is secure but the certificate is not valid or from a trusted certificate?

Any help on this would be appreciated.

Many thanks

**Comment by adviserportals** [comment]
Just a follow up to the above...

After some time, if I then go back to a site that had the above issue, it seems to work. Most odd.

There does not appear to be any specific reason as to why a site would have this issue and then later on it goes away?

Cheers

**Comment by rekby** [comment]
Hello.
It is very small information for I can answer for you :(
It might be temporary error while domain check.
Or may be you change ip address of domain and not all DNS updated - then lets-proxy or letsencrypt has fail check domain while cert issue.
