### ISSUE TITLE
where is the documentation?

### ISSUE THREAD

**Issue by JustinWebDev** [rekby/lets-proxy2#168]
Maybe I'm blind, but I don't see any link to documentation, and `lets-proxy.exe --help` doesn't show much.

**Comment by rekby** [comment]
Hello.
It hasn't dedicated documentation now.

You can see Commented [default config](https://github.com/rekby/lets-proxy2/blob/0ce81e5e5948c83d8d7ef8ef2d1d62baab1dd902/cmd/static/default-config.toml).

It available by command:
```
lets-proxy2 --print-default-config

or write to file:
let-proxy2 --print-default-config > default_config.toml
```

It is help to you?

**Comment by JustinWebDev** [comment]
It is helpful, but not complete.  I don't know how to interpret some of the settings, some look like duplicate values, and some look incomplete.

My main two concerns right now (to just get a working system), are:
1. How to config a reverse proxy.
2. How to define the "main domain" (mydomain.com) for TLS certs.  I see where subdomains are defined.

And, why would someone use lets-proxy_windows_amd64.zip vs lets-proxy_windows_amd64-go1.10.zip?

**Comment by rekby** [comment]
If you want just reverse-proxy without specials - you can simple start lets-proxy.exe ([start as service](https://github.com/rekby/lets-proxy2/wiki#run-as-service-in-windows) - as option) without any config.

The lets-proxy will handle all requests to https on standard 443 on all IPs port, decrypt it, then forward as http request to port 80 same IP. It no need any special config or list your domain and subdomains.

For example - you have server with IP 1.2.3.4.
1. You start lets-proxy.exe (without any config/options etc). It will listen on 1.2.3.4:443.
2. Somebody will request to your domain https://domain.com (domain as A record in dns to ip 1.2.3.4).
3. lets-proxy accept the request, check A record for domain.com, get TLS cert from lets-proxy for domain domain.com
4. proxy the request to 1.2.3.4:80 as http-request (and set some additional headers about original request).

**Comment by rekby** [comment]
lets-proxy_windows_amd64-go1.10.zip need only for old system (for example windows 2013), go 1.11 and newer doesn't support old OS and program, compiled from newer language version often crash or even can't start.

**Comment by JustinWebDev** [comment]
Each subdomain maps to a different service, so I can't use the OOTB configuration.  I'll have to specify a service for each subdomain.

(The info you gave though is very helpful in understanding its basic operation.  Thanks.)

**Comment by rekby** [comment]
lets proxy support only docker by-domain balance (redirect traffic to [docker container](https://github.com/rekby/lets-proxy2/blob/0ce81e5e5948c83d8d7ef8ef2d1d62baab1dd902/cmd/static/default-config.toml#L161) with special label), but doesn't support manual per-domain redirect.

For solve the problem per-domain redirect you can use lets proxy for handle https, then other software (nginx/envoy) for per domain balance http traffic.

**Comment by JustinWebDev** [comment]
That's disappointing to hear.  Thanks for the info.
