### ISSUE TITLE
// in url -> 'silent' 301 converting POST to get

### ISSUE THREAD

**Issue by TyberiusPrime** [rekby/lets-proxy2#177]
When an URL contains double '/',
the proxy issues a 301 redirect to a GET on the url without '/', discarding
POST data.

It also doesn't log the POST either.

**Comment by rekby** [comment]
@TyberiusPrime Thanks for bug report.
I fixed it, try version https://github.com/rekby/lets-proxy2/releases/tag/v0.26.2

**Comment by TyberiusPrime** [comment]
Thank you!
I can confirm that this fixes the issue.
