### ISSUE TITLE
Switch to ACME V2

### ISSUE THREAD

**Issue by rekby** [rekby/lets-proxy2#73]
Because https://community.letsencrypt.org/t/end-of-life-plan-for-acmev1/88430

**Comment by rekby** [comment]
Wait https://github.com/golang/go/issues/21081

**Comment by rekby** [comment]
https://github.com/golang/go/issues/21081 closed.

Need update dependency and tests

**Comment by OloBo-MSK** [comment]
Hello. Any news?

**Comment by rekby** [comment]
Hello, yes.
I start switch to new protocol.
