### ISSUE TITLE
How to use minwinsvc

### ISSUE THREAD

**Issue by joeblew99** [rekby/lets-proxy2#80]
I saw the commits for minwinsvc. Thanks

Not sue how to invoke it on Mac or Windows to install and uninstall as a Service.

**Comment by joeblew99** [comment]
Gitea also use the same approach with minwinsvc-

https://docs.gitea.io/en-us/windows-service/

**Comment by rekby** [comment]
Hello.

You can install lets-proxy as service for windows same way:
```
sc create lets-proxy start= auto binPath= ""c:\programs\lets-proxy\lets-proxy.exe" --config="c:\programs\lets-proxy\config.toml""
```

I don't know any about service commands on macos.

**Comment by rekby** [comment]
I think to write it for wiki https://github.com/rekby/lets-proxy2/issues/81
